### ISSUE TITLE
wifite --kill --keep-ivs -mac --bully --pmkid -i wlan0mon -v --dic /usr/share/wordlists/rockyou.txt --require-fakeauth --nodeauth -p 1337 --wps --pmkid-timeout 120

### ISSUE THREAD

**Issue by princelovers76** [gentoo-root/certbot-dns-henet#4]
wifite --kill --keep-ivs -mac --bully --pmkid -i wlan0mon -v --dic /usr/share/wordlists/rockyou.txt --require-fakeauth --nodeauth -p 1337 --wps --pmkid-timeout 120

_Originally posted by @Daniels8989 in https://github.com/derv82/wifite2/pull/288_

**Comment by gentoo-root** [comment]
What is it?
